[project]
name = "fastapi-example"
version = "0.1.0"
description = "FastAPI example project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
]
[tool.pyright]
venvPath = "."
venv = ".venv"
