[project]
name = "app"
version = "0.1.0"
description = "FastAPI example project"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.128.0",
    "slowapi>=0.1.9",
    "starlette-csrf>=3.0.0",
]
[tool.pyright]
venvPath = "."
venv = ".venv"
